YCPRadioTelescope/YCP-RT-ControlRoom

ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/AbstractPLCDriver.cs
ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/ProductionMCUDriver.cs
ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/ProductionPLCDriver.cs
ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/ScaleModelPLCDriver.cs
ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/SimulationPLCDriver.cs
ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/TestPLCDriver.cs
ControlRoomApplication/ControlRoomApplication/Entities/HeartbeatInterface/HeartbeatTracker.cs
ControlRoomApplication/ControlRoomApplication/Entities/HeartbeatInterface/HeartbeatTrackerContainer.cs
ControlRoomApplication/ControlRoomApplication/External_Controlers/scalePLCArdrionCode/RTCode.ino
ControlRoomApplication/ControlRoomApplication/GUI/MainForm.cs
ControlRoomApplication/ControlRoomApplication/Simulators/Hardware/PLC_MCU/Simulation_control_pannel.cs
ControlRoomApplication/ControlRoomApplicationTest/EntitiesTests/ControlRoomTest.cs
ControlRoomApplication/ControlRoomApplicationTest/EntitiesTests/HeartbeatTrackerContainerTest.cs
ControlRoomApplication/ControlRoomApplicationTest/EntityControllersTests/AbstractPLCDriverTest.cs
ControlRoomApplication/ControlRoomApplicationTest/EntityControllersTests/ControlRoomControllerTest.cs
ControlRoomApplication/ControlRoomApplicationTest/EntityControllersTests/PLCClientAndDriverTest.cs
ControlRoomApplication/ControlRoomApplicationTest/EntityControllersTests/RadioTelescopeControllerManagementThreadTest.cs
ControlRoomApplication/ControlRoomApplicationTest/EntityControllersTests/RadioTelescopeControllerTest.cs

fixed unit tests and add basic funcitionality to scale plc code

Scale plc rework2

---

ControlRoomApplication/ControlRoomApplication/Constants/SimulationConstants.cs
ControlRoomApplication/ControlRoomApplication/ControlRoomApplication.csproj
ControlRoomApplication/ControlRoomApplication/Controllers/BlkHeadUcontroler/SimulatedEncoder.cs
ControlRoomApplication/ControlRoomApplication/Controllers/BlkHeadUcontroler/SimulatedMicrocontroller.cs
ControlRoomApplication/ControlRoomApplication/Controllers/Sensors/FakeEncoderSensor.cs
ControlRoomApplication/ControlRoomApplication/Controllers/Sensors/FakeTempSensor.cs
ControlRoomApplication/ControlRoomApplication/GUI/DiagnosticsForm.cs
ControlRoomApplication/ControlRoomApplication/GUI/MainForm.cs

Update sensor sim

---

ControlRoomApplication/ControlRoomApplication/Entities/WeatherStation/AbstractWeatherStation.cs
ControlRoomApplication/ControlRoomApplication/Entities/WeatherStation/WeatherStation.cs
ControlRoomApplication/ControlRoomApplication/GUI/DiagnosticsForm.cs
ControlRoomApplication/ControlRoomApplication/Simulators/Hardware/WeatherStation/SimulationWeatherStation.cs

The simulated weather station now has the ability to change the values approximately every 30 seconds. The values are based upon averages and maximum values found through various sites online. These do not have to be accurate, but rather showcase an acceptable range of values.

Adding functionality of Simulated Weather Station

---

ControlRoomApplication/ControlRoomApplication/Entities/WeatherStation/WeatherStation.cs
ControlRoomApplication/ControlRoomApplication/GUI/DiagnosticsForm.Designer.cs
ControlRoomApplication/ControlRoomApplication/GUI/DiagnosticsForm.cs
ControlRoomApplication/ControlRoomApplication/Simulators/Hardware/WeatherStation/SimulationWeatherStation.cs

Fixing bugs with weather station display on gui

Weather station

---

ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/AbstractPLCDriver.cs
ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/ProductionMCUDriver.cs
ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/ProductionPLCDriver.cs
ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/ScaleModelPLCDriver.cs
ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/SimulationPLCDriver.cs
ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/TestPLCDriver.cs

Adding the hit hardware stops scripts

Adding hit hardware stop functionality

---

ControlRoomApplication/ControlRoomApplication/GUI/DiagnosticsForm.Designer.cs
ControlRoomApplication/ControlRoomApplication/GUI/DiagnosticsForm.cs
ControlRoomApplication/ControlRoomApplication/GUI/MainForm.Designer.cs
ControlRoomApplication/ControlRoomApplication/GUI/MainForm.cs

Basically the final version of the User interface

More changes to GUI functionality

---

ControlRoomApplication/ControlRoomApplication/GUI/MainForm.cs
ControlRoomApplication/ControlRoomApplication/GUI/RTControlForm.cs
ControlRoomApplication/ControlRoomApplication/GUI/RTControlForm.designer.cs

 fixing a few bugs

---

ControlRoomApplication/ControlRoomApplication/Simulators/Hardware/WeatherStation/SimulationWeatherStation.cs

Fixing simulation weather station wind speed generation

---

ControlRoomApplication/ControlRoomApplication/ControlRoomApplication.csproj
ControlRoomApplication/ControlRoomApplication/Controllers/AASharpControllers/CoordinateCalculationController.cs
ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/MCUManager.cs
ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/ProductionPLCDriver.cs
ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCEvents.cs
ControlRoomApplication/ControlRoomApplication/Controllers/RadioTelescopeControllers/RadioTelescopeController.cs
ControlRoomApplication/ControlRoomApplication/Entities/Exceptions/MCUExceptions.cs
ControlRoomApplication/ControlRoomApplication/Entities/PLC/PLCCommandAndQueryTypeEnum.cs

fix for issue #18 
as well as adding connectivity checking to MCU

add MCU heartbeat to PLC

---

ControlRoomApplication/ControlRoomApplication/Constants/MiscellaneousConstants.cs
ControlRoomApplication/ControlRoomApplication/Controllers/AASharpControllers/CoordinateCalculationController.cs
ControlRoomApplication/ControlRoomApplication/Controllers/ControlRoomController/RadioTelescopeControllerManagementThread.cs
ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/AbstractPLCDriver.cs
ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/ProductionPLCDriver.cs
ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/ScaleModelPLCDriver.cs
ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/SimulationPLCDriver.cs
ControlRoomApplication/ControlRoomApplication/Controllers/RadioTelescopeControllers/RadioTelescopeController.cs
ControlRoomApplication/ControlRoomApplication/Database/Operations/DatabaseOperations.cs
ControlRoomApplication/ControlRoomApplication/Entities/Appointment/Appointment.cs
ControlRoomApplication/ControlRoomApplication/GUI/MainForm.cs
ControlRoomApplication/ControlRoomApplication/GUI/RTControlForm.cs
ControlRoomApplication/ControlRoomApplicationTest/DatabaseOperationsTests/DatabaseOperationsTests.cs
ControlRoomApplication/ControlRoomApplicationTest/DatabaseOperationsTests/RTDbContextTests.cs
ControlRoomApplication/ControlRoomApplicationTest/EntitiesTests/AppointmentTest.cs
ControlRoomApplication/ControlRoomApplicationTest/EntitiesTests/HeartbeatInterfaceTests/ConcreteHeartbeatTestClass.cs
ControlRoomApplication/ControlRoomApplicationTest/EntitiesTests/HeartbeatInterfaceTests/HeartbeatInterfaceTest.cs
ControlRoomApplication/ControlRoomApplicationTest/EntitiesTests/HeartbeatTrackerContainerTest.cs
ControlRoomApplication/ControlRoomApplicationTest/EntityControllersTests/ControlRoomControllerTest.cs
ControlRoomApplication/ControlRoomApplicationTest/EntityControllersTests/CoordinateCalculationControllerTest.cs
ControlRoomApplication/ControlRoomApplicationTest/EntityControllersTests/RadioTelescopeControllerTest.cs

Fixing tests, fixing hang in script call, adding tests, fixing appointment data

Database connection

---

ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/MCUManager.cs
ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/ProductionPLCDriver.cs
ControlRoomApplication/ControlRoomApplication/Controllers/RadioTelescopeControllers/RadioTelescopeController.cs
ControlRoomApplication/ControlRoomApplication/GUI/RTControlForm.cs
ControlRoomApplication/ControlRoomApplication/Simulators/Hardware/PLC_MCU/Simulation_control_pannel.cs
ControlRoomApplication/ControlRoomApplicationTest/EntityControllersTests/RadioTelescopeControllerTest.cs

changes for simulator and software stops

Software stop

---

ControlRoomApplication/ControlRoomApplication/Controllers/RadioTelescopeControllers/RadioTelescopeController.cs
ControlRoomApplication/ControlRoomApplication/GUI/DiagnosticsForm.Designer.cs
ControlRoomApplication/ControlRoomApplication/GUI/DiagnosticsForm.cs
ControlRoomApplication/ControlRoomApplication/GUI/MainForm.cs
ControlRoomApplication/ControlRoomApplication/GUI/RTControlForm.cs
ControlRoomApplication/ControlRoomApplication/GUI/RTControlForm.designer.cs

diagnosticsForm now works again because we're no longer using [rtId-1].

Override integration

---

.gitignore
ControlRoomApplication/ControlRoomApplication/ControlRoomApplication.csproj
ControlRoomApplication/ControlRoomApplication/Controllers/ControlRoomController/ControlRoomController.cs
ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/ProductionPLCDriver.cs
ControlRoomApplication/ControlRoomApplication/Controllers/RadioTelescopeControllers/RadioTelescopeController.cs
ControlRoomApplication/ControlRoomApplication/GUI/DiagnosticsForm.cs

This does not include the pushNotification.cs file.

Added implementation for push notifications.

---

ControlRoomApplication/ControlRoomApplication/Controllers/ControlRoomController/ControlRoomController.cs
ControlRoomApplication/ControlRoomApplication/Controllers/RadioTelescopeControllers/RadioTelescopeController.cs
ControlRoomApplication/ControlRoomApplication/Controllers/TCPCommunication/RemoteListener.cs
ControlRoomApplication/ControlRoomApplication/Entities/ControlRoom/ControlRoom.cs
ControlRoomApplication/ControlRoomApplication/GUI/DiagnosticsForm.Designer.cs
ControlRoomApplication/ControlRoomApplication/GUI/DiagnosticsForm.cs
ControlRoomApplication/ControlRoomApplication/GUI/MainForm.cs
ControlRoomApplication/ControlRoomApplicationTest/EntityControllersTests/ControlRoomControllerTest.cs

Made diagnostics form overrides more efficient, implemented overrides on middleman, updated test cases.

Middleman overrides now exist

---

ControlRoomApplication/ControlRoomApplication/ControlRoomApplication.csproj
ControlRoomApplication/ControlRoomApplication/Controllers/ControlRoomController/ControlRoomController.cs
ControlRoomApplication/ControlRoomApplication/Controllers/ControlRoomController/RadioTelescopeControllerManagementThread.cs
ControlRoomApplication/ControlRoomApplication/Controllers/RadioTelescopeControllers/RadioTelescopeController.cs
ControlRoomApplication/ControlRoomApplication/Controllers/Sensors/OverrideSwitchData.cs
ControlRoomApplication/ControlRoomApplication/Controllers/TCPCommunication/RemoteListener.cs
ControlRoomApplication/ControlRoomApplication/Database/Operations/DatabaseOperations.cs
ControlRoomApplication/ControlRoomApplication/Database/RTDbContext.cs
ControlRoomApplication/ControlRoomApplication/Entities/ControlRoom/ControlRoom.cs
ControlRoomApplication/ControlRoomApplication/Entities/Override/Override.cs
ControlRoomApplication/ControlRoomApplication/Entities/Sensor/SensorItemEnum.cs
ControlRoomApplication/ControlRoomApplication/Entities/Sensor/ThresholdValues.cs
ControlRoomApplication/ControlRoomApplication/Entities/WeatherStation/AbstractWeatherStation.cs
ControlRoomApplication/ControlRoomApplication/GUI/DiagnosticsForm.cs
ControlRoomApplication/ControlRoomApplication/GUI/RTControlForm.cs
ControlRoomApplication/ControlRoomApplicationTest/DatabaseOperationsTests/DatabaseOperationsTests.cs
ControlRoomApplication/ControlRoomApplicationTest/EntityControllersTests/RadioTelescopeControllerTest.cs

- pull threshold data and use that to compare to actual readings to see if we are out of range
- pull override data
- push override data when control room makes a change

Sensor Thresholds/Override Database connection

---

ControlRoomApplication/ControlRoomApplication/Controllers/Communications/SNSMessage.cs
ControlRoomApplication/ControlRoomApplication/Controllers/ControlRoomController/RadioTelescopeControllerManagementThread.cs
ControlRoomApplication/ControlRoomApplication/Database/Operations/DatabaseOperations.cs
ControlRoomApplication/ControlRoomApplication/Database/RTDbContext.cs
ControlRoomApplication/ControlRoomApplication/Entities/Appointment/Appointment.cs
ControlRoomApplication/ControlRoomApplication/Entities/Appointment/AppointmentStatusEnum.cs
ControlRoomApplication/ControlRoomApplication/Entities/RadioTelescope/RadioTelescope.cs
ControlRoomApplication/ControlRoomApplication/Entities/SpectraCyber/SpectraCyberBandwidthEnum.cs
ControlRoomApplication/ControlRoomApplication/Entities/SpectraCyber/SpectraCyberConfig.cs
ControlRoomApplication/ControlRoomApplication/GUI/MainForm.cs

This pr has small database changes to work with the cluster db. But one major change that we initially pull a radio telescope from the database at the start of an RT. We do this to not create multiple telescopes so the id does not change for the backend and frontend as it is hardcoded on their end

Database issues

---

.gitignore
ControlRoomApplication/ControlRoomApplication/ControlRoomApplication.csproj
ControlRoomApplication/ControlRoomApplication/Controllers/Communications/SNSMessage.cs
ControlRoomApplication/ControlRoomApplication/Controllers/ControlRoomController/ControlRoomController.cs
ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/ProductionPLCDriver.cs
ControlRoomApplication/ControlRoomApplication/Controllers/RadioTelescopeControllers/RadioTelescopeController.cs
ControlRoomApplication/ControlRoomApplication/GUI/DiagnosticsForm.cs
ControlRoomApplication/ControlRoomApplicationTest/CommunicationTests/PushNoficiationTest.cs
ControlRoomApplication/ControlRoomApplicationTest/ControlRoomApplicationTest.csproj
README.md

Moved push notifications into the correct folder; updated any imports.

Moved PushNotification.cs into its correct location; updated imports

---

ControlRoomApplication/ControlRoomApplication/Database/Operations/DatabaseOperations.cs
ControlRoomApplication/ControlRoomApplication/Entities/Coordinate/Coordinate.cs
ControlRoomApplication/ControlRoomApplication/Entities/Orientation/Orientation.cs
ControlRoomApplication/ControlRoomApplicationTest/CommunicationTests/PushNoficiationTest.cs
ControlRoomApplication/ControlRoomApplicationTest/CommunicationTests/PushNotificationTest.cs
ControlRoomApplication/ControlRoomApplicationTest/DatabaseOperationsTests/DatabaseOperationsTests.cs
ControlRoomApplication/ControlRoomApplicationTest/EntityControllersTests/ControlRoomControllerTest.cs
ControlRoomApplication/ControlRoomApplicationTest/EntityControllersTests/CoordinateCalculationControllerTest.cs
ControlRoomApplication/ControlRoomApplicationTest/EntityControllersTests/RadioTelescopeControllerTest.cs

All tests have been fixed and missing features added, with the exception of `TestConstructorsAndProperties`, which will be covered in Issue #164.

Test case fix

---

ControlRoomApplication/ControlRoomApplication/Database/Operations/DatabaseOperations.cs
ControlRoomApplication/ControlRoomApplication/Entities/RadioTelescope/RadioTelescope.cs
ControlRoomApplication/ControlRoomApplication/GUI/MainForm.cs
ControlRoomApplication/ControlRoomApplicationTest/ControlRoomApplicationTest.csproj
ControlRoomApplication/ControlRoomApplicationTest/EntityControllersTests/RadioTelescopeControllerManagementThreadTest.cs

Telescope create integration

---

.gitignore
ControlRoomApplication/ControlRoomApplication/ControlRoomApplication.csproj
ControlRoomApplication/ControlRoomApplication/Controllers/Communications/SNSMessage.cs
ControlRoomApplication/ControlRoomApplication/Database/Operations/DatabaseOperations.cs
ControlRoomApplication/ControlRoomApplication/packages.config
ControlRoomApplication/ControlRoomApplicationTest/CommunicationTests/PushNotificationTest.cs
ControlRoomApplication/ControlRoomApplicationTest/ControlRoomApplicationTest.csproj
ControlRoomApplication/ControlRoomApplicationTest/packages.config

The control room application now had the functionality of sending emails from within the application's code via the AWS SES API.

Implemented email notifications

---

ControlRoomApplication/ControlRoomApplication/Constants/MiscellaneousConstants.cs
ControlRoomApplication/ControlRoomApplication/Database/Operations/DatabaseOperations.cs
ControlRoomApplication/ControlRoomApplication/Entities/Location/Location.cs
ControlRoomApplication/ControlRoomApplication/Entities/RadioTelescope/RadioTelescope.cs
ControlRoomApplication/ControlRoomApplication/GUI/MainForm.cs

Location was made a foreign key to a radio_telescope.
Issue #184

Made a Telescope's location loaded from the database

---

ControlRoomApplication/ControlRoomApplication/GUI/DiagnosticsForm.Designer.cs
ControlRoomApplication/ControlRoomApplication/GUI/DiagnosticsForm.cs

Issue #187
Removed old code that was not needed and added color to the constructor.

Fixed temperature conversion in diagnostic form

---

ControlRoomApplication/ControlRoomApplication/Constants/MiscellaneousConstants.cs
ControlRoomApplication/ControlRoomApplication/ControlRoomApplication.csproj
ControlRoomApplication/ControlRoomApplication/GUI/DiagnosticsForm.Designer.cs
ControlRoomApplication/ControlRoomApplication/GUI/EditDiagScriptsForm.Designer.cs
ControlRoomApplication/ControlRoomApplication/GUI/EditDiagScriptsForm.cs
ControlRoomApplication/ControlRoomApplication/GUI/EditTestForm.Designer.cs
ControlRoomApplication/ControlRoomApplication/GUI/EditTestForm.cs
ControlRoomApplication/ControlRoomApplication/GUI/MainForm.Designer.cs
ControlRoomApplication/ControlRoomApplication/GUI/MainForm.cs
ControlRoomApplication/ControlRoomApplication/GUI/MainForm.resx
ControlRoomApplication/ControlRoomApplication/GUI/ManualControl.Designer.cs
ControlRoomApplication/ControlRoomApplication/GUI/ManualControl.cs
ControlRoomApplication/ControlRoomApplication/GUI/RTControlForm.cs
ControlRoomApplication/ControlRoomApplication/GUI/RTControlForm.designer.cs
ControlRoomApplication/ControlRoomApplication/GUI/RTControlForm.resx
ControlRoomApplication/ControlRoomApplication/Util/Validator.cs
ControlRoomApplication/ControlRoomApplicationTest/ControlRoomApplicationTest.csproj
ControlRoomApplication/ControlRoomApplicationTest/Util Tests/ValidatorTests.cs

These are the files that I did not git add last time. These changes include fully implemented user validation for both MainForm and RTControlForm, along with minor tweaks to the Dropdown lists on the form to display the "select" option by default.

Validation class & GUI form validation fixes

---

ControlRoomApplication/ControlRoomApplication/Database/Operations/DatabaseOperations.cs
ControlRoomApplication/ControlRoomApplication/GUI/MainForm.cs
ControlRoomApplication/ControlRoomApplicationTest/DatabaseOperationsTests/DatabaseOperationsTests.cs

Allowed telescope online status to change in the databse. Added alert
messages for telescope running. Added tests as well.
Issue #206

Update telescope online status

---

ControlRoomApplication/ControlRoomApplication/Database/Operations/DatabaseOperations.cs

Hotfix: test code no longer being executed in production

---

ControlRoomApplication/ControlRoomApplication/Controllers/SpectraCyberControllers/AbstractSpectraCyberController.cs
ControlRoomApplication/ControlRoomApplication/Database/Operations/DatabaseOperations.cs

- Added Telescope orientations to fetch radio telescope
- Fixed stop RT (for real this time)

Stop rt fix 2

---

ControlRoomApplication/ControlRoomApplication/GUI/MainForm.cs

Allows user to override running telescope/ fix crash issues
Issue #237

Override for online telescope

---

ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/MCUManager.cs
ControlRoomApplication/ControlRoomApplication/Controllers/RadioTelescopeControllers/RadioTelescopeController.cs

Fixed console spelling error "incoming"

McuManager spelling

---

ControlRoomApplication/ControlRoomApplicationTest/DatabaseOperationsTests/DatabaseOperationsTests.cs

Created 2 Temperature Tests in DatabaseOperations for Issue #211

Created 2 Temperature Tests

---

ControlRoomApplication/ControlRoomApplication/GUI/MainForm.Designer.cs
ControlRoomApplication/ControlRoomApplication/GUI/MainForm.cs
ControlRoomApplication/ControlRoomApplication/GUI/MainForm.resx

Updated the mainform to include the sensor network logic
Issue #271

Main form update

---

ControlRoomApplication/ControlRoomApplication/GUI/DiagnosticsForm.Designer.cs
ControlRoomApplication/ControlRoomApplication/GUI/DiagnosticsForm.cs

Added the new buttons and checkboxes to the diagnosti form
Issue #273

Updated Diagnostic Form

---

ControlRoomApplication/ControlRoomApplication/ControlRoomApplication.csproj
ControlRoomApplication/ControlRoomApplication/GUI/MainForm.cs
ControlRoomApplication/ControlRoomApplication/GUI/ManualControl.cs
ControlRoomApplication/ControlRoomApplication/GUI/RTControlForm.cs
ControlRoomApplication/ControlRoomApplication/GUI/RTControlForm.designer.cs
ControlRoomApplication/ControlRoomApplication/GUI/RTControlFormData.cs
ControlRoomApplication/ControlRoomApplication/Util/Utilities.cs

Completed implementation of the RTControlForm not retaining data after being opened and closed.

Retain data

---

ControlRoomApplication/ControlRoomApplication/Entities/DiagnosticData/Temperature.cs
ControlRoomApplication/ControlRoomApplicationTest/ControlRoomApplicationTest.csproj
ControlRoomApplication/ControlRoomApplicationTest/EntitiesTests/TemperatureTest.cs

Added IEEquatable and added Juinit testing
Issue #265

Impliment IEquatable in Temperature

---

ControlRoomApplication/ControlRoomApplication/GUI/RTControlForm.cs
ControlRoomApplication/ControlRoomApplication/GUI/RTControlForm.designer.cs

Implemented endless AZ script from scratch, for hopefully the last time

---

ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/ProductionPLCDriver.cs

It now moves to Azimuth and THEN to Elevation, dumps the snow and returns to original location.

Fixed Snow Dump Script moving Azimuth & Elevation at the same time.

---

ControlRoomApplication/ControlRoomApplication/ControlRoomApplication.csproj
ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/MCUManager/MovePriority.cs

Added MovePriority enum for the MCUManager

---

ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/MCUManager/MCUManager.cs
ControlRoomApplication/ControlRoomApplication/GUI/MainForm.cs
ControlRoomApplication/ControlRoomApplication/GUI/MainForm.resx
ControlRoomApplication/ControlRoomApplication/Util/Validator.cs
ControlRoomApplication/ControlRoomApplicationTest/Util Tests/ValidatorTests.cs

This PR includes:
- Connection to the MCU does not throw an exception if it fails (allows the user to retry)
- Elevation homing routine update

Mcu connect fix

---

ControlRoomApplication/ControlRoomApplication/GUI/RTControlForm.cs
ControlRoomApplication/ControlRoomApplication/GUI/RTControlForm.designer.cs

Set default manual control

---

ControlRoomApplication/ControlRoomApplication/Controllers/BlkHeadUcontroler/AbstractMicrocontroller.cs
ControlRoomApplication/ControlRoomApplication/Controllers/BlkHeadUcontroler/SimulatedMicrocontroller.cs
ControlRoomApplication/ControlRoomApplication/Controllers/SensorNetwork/SensorNetworkServer.cs
ControlRoomApplication/ControlRoomApplication/Database/Operations/DatabaseOperations.cs
ControlRoomApplication/ControlRoomApplicationTest/DatabaseOperationsTests/DatabaseOperationsTests.cs

Added Temperature and Acceleration to the database. Updated
DatabaseOperations to accept arrays along with tests too.
Issue #338

Add Temperature and Accelertation to Database

---

ControlRoomApplication/ControlRoomApplication/Controllers/Communications/RemoteListener.cs
ControlRoomApplication/ControlRoomApplicationTest/CommunicationTests/RemoteListenerTest.cs
ControlRoomApplication/ControlRoomApplicationTest/ControlRoomApplicationTest.csproj

Added sensor network init update to Remote Listener & test

---

ControlRoomApplication/ControlRoomApplication/Controllers/Communications/RemoteListener.cs
ControlRoomApplication/ControlRoomApplicationTest/CommunicationTests/RemoteListenerTest.cs

Also added unit tests for all the overrides. This will be a good start
for getting the rest of Remote Listener unit tested.
Issue #374, #299

Added new sensor overrides to Remote Listener

---

ControlRoomApplication/ControlRoomApplication/Entities/WeatherStation/WeatherStation.cs

Previously, since the functionality was in a do-while loop, it could (in theory) retry the update infinitely. We want to cap this at a maximum of 4 tries before abandoning the update.
-Added a counter to ensure the weather station data tries a maximum of 4 times to update the database with the current weather station data, if it runs into the Entity Exception.
-Added logic inside the do-while loop to handle this, and added a logger statement to inform the user when the update will be abandoned if the retry does, in fact, fail 4 times.

Weather Station data DBUpdate Fix

---

ControlRoomApplication/ControlRoomApplication/ControlRoomApplication.csproj
ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/AbstractPLCDriver.cs
ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/MCUManager/Enumerations/MovementResult.cs
ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/MCUManager/MCUManager.cs
ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/ProductionPLCDriver.cs
ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/ScaleModelPLCDriver.cs
ControlRoomApplication/ControlRoomApplication/Controllers/PLCCommunication/PLCDrivers/SimulationPLCDriver.cs
ControlRoomApplication/ControlRoomApplication/Controllers/RadioTelescopeControllers/RadioTelescopeController.cs
ControlRoomApplication/ControlRoomApplicationTest/EntityControllersTests/RadioTelescopeControllerTest.cs

- Movements now return a result instead of true/false
- Updated scripts that use multiple movements to return right away after a failed movement

Mcu manager enhancements

---

ControlRoomApplication/ControlRoomApplication/ControlRoomApplication.csproj
ControlRoomApplication/ControlRoomApplication/Controllers/SensorNetwork/SensorNetworkServer.cs
ControlRoomApplication/ControlRoomApplication/Database/Operations/DatabaseOperations.cs
ControlRoomApplication/ControlRoomApplication/Database/RTDbContext.cs
ControlRoomApplication/ControlRoomApplication/Entities/Acceleration/AccelerationBlob.cs
ControlRoomApplication/ControlRoomApplicationTest/ControlRoomApplicationTest.csproj
ControlRoomApplication/ControlRoomApplicationTest/DatabaseOperationsTests/DatabaseOperationsTests.cs
ControlRoomApplication/ControlRoomApplicationTest/EntitiesTests/AccelerationBlobTest.cs

Added the AccelerationBlob class. Added a function that splits up acceleration data. Added tests as well.
Issue #371

AccelerationBlob and tests

---

.gitignore
ControlRoomApplication/ControlRoomApplication.sln
ControlRoomApplication/ControlRoomApplication/Constants/MiscellaneousConstants.cs
ControlRoomApplication/ControlRoomApplication/ControlRoomApplication.csproj
ControlRoomApplication/ControlRoomApplication/Controllers/SensorNetwork/SensorNetworkServer.cs
ControlRoomApplication/ControlRoomApplication/Database/Operations/DatabaseOperations.cs
ControlRoomApplication/ControlRoomApplication/Database/RTDbContext.cs
ControlRoomApplication/ControlRoomApplication/Entities/Acceleration/AccelerationBlob.cs
ControlRoomApplication/ControlRoomApplication/Entities/Acceleration/AzimuthAccelerationBlob.cs
ControlRoomApplication/ControlRoomApplication/Entities/Acceleration/CounterbalanceAccelerationBlob.cs
ControlRoomApplication/ControlRoomApplication/Entities/Acceleration/ElevationAccelerationBlob.cs
ControlRoomApplication/ControlRoomApplication/Entities/DiagnosticData/Acceleration.cs
ControlRoomApplication/ControlRoomApplication/Entities/Location/SensorLocationEnum.cs
ControlRoomApplication/ControlRoomApplicationTest/DatabaseOperationsTests/DatabaseOperationsTests.cs
ControlRoomApplication/ControlRoomApplicationTest/EntitiesTests/AccelerationBlobTest.cs
ControlRoomApplication/ControlRoomApplicationTest/EntitiesTests/AccelerationTest.cs

Pull request to add the redesigned acceleration blob into the CR. 
Note: the database has been modified with this update, so it will have to be rebuilt in order for the CR to function.  A PR will be added for those changes soon.

Acceleration blob

---

ControlRoomApplication/ControlRoomApplication/Controllers/Communications/RemoteListener.cs
ControlRoomApplication/ControlRoomApplicationTest/CommunicationTests/RemoteListenerTest.cs

Set and send weather data in TCP

Tcp Data Enhancement

---

ControlRoomApplication/ControlRoomApplication/GUI/DiagnosticsForm.cs

Change overriding to disabled on the diagnostics form. :)

---

ControlRoomApplication/ControlRoomApplication/ControlRoomApplication.csproj
ControlRoomApplication/ControlRoomApplication/Controllers/Communications/pushNotification.cs
ControlRoomApplication/ControlRoomApplication/Controllers/RadioTelescopeControllers/RadioTelescopeController.cs
ControlRoomApplication/ControlRoomApplication/Entities/Encoder/EncoderAverages.cs
ControlRoomApplication/ControlRoomApplicationTest/ControlRoomApplicationTest.csproj
ControlRoomApplication/ControlRoomApplicationTest/EntitiesTests/EncoderAveragesTest.cs

Fix encoders too far apart error
